

# This file contains the different path to the dataset, depending on the PC the code is running

tiago-deep: '/home/tiago/Dropbox/research/datasets'
root: '/home/tiago/Dropbox/research-projects/orchards-uk/dataset'
root_ws: 'C:\\Users\\Tiago\\TB\\datasets'
deep-MS-7C37: "/home/deep/Dropbox/SHARE/DATASET"
tiago-SATELLITE-P50-C: "/home/tiago/Dropbox/SHARE/DATASET"
beast: "/home/beast/Dropbox/SHARE/DATASET"
