

experim_name: 'default'
################################################################################
# training parameters
################################################################################
pretrained_root: 'checkpoints'
n_gpu: 1

retrieval:
  top_cand: [1,5,25]
  range_thres: 6

max_points: 10000 # Maximum number of points to be used in the network
aug: False # Augment data with rotations 

base_dir: "uk"
memory: "DISK"
modality: "bev"

cross_validation: 
            'orchards/sum22/extracted': ['orchards/june23/extracted','orchards/aut22/extracted','strawberry/june23/extracted']
            'orchards/june23/extracted': ['orchards/sum22/extracted','orchards/aut22/extracted','strawberry/june23/extracted']
            'orchards/aut22/extracted': ['orchards/sum22/extracted','orchards/june23/extracted','strawberry/june23/extracted']
            'strawberry/june23/extracted': ['orchards/sum22/extracted','orchards/june23/extracted','orchards/aut22/extracted']

split:
  split_ratio: 0.95
  sequences: ['orchards/sum22/extracted',
              'orchards/june23/extracted',
              'orchards/aut22/extracted',
              'strawberry/june23/extracted'] 

row_label_file: "point_row_labels.pkl"
# Ground-truth parameters
ground_truth:
  orchards/june23:
    pos_range: 2 # Loop Threshold [m]
    neg_range: 10
    warmupitrs: 200 # Number of frames to ignore at the beguinning
    roi: 100

  strawberry/june23:
    pos_range: 2 # Loop Threshold [m]
    neg_range: 10
    warmupitrs: 200 # Number of frames to ignore at the beguinning
    roi: 100
    triplet_files: 'ground_truth_ar2m_nr20m_pr2m.npz'

  orcahrds/sum22:
    pos_range: 2 # Loop Threshold [m]
    neg_range: 10
    warmupitrs: 500 # Number of frames to ignore at the beguinning
    roi: 400

# Dataset parameters
train_loader:
  triplet_file: 'triplet/ground_truth_ar0.5m_nr10m_pr2m.pkl'
  sequence: [
            'orchards/sum22/extracted',
            'orchards/june23/extracted',
            'orchards/aut22/extracted',
            #'strawberry/june23/extracted'
            ]

  fraction: 0.3 
  batch_size: 1       # batch size
  shuffle: True
  num_pos: 1
  num_neg: 20

  #rotation: [180,-45,-45]
  
val_loader:
  ground_truth_file: "eval/ground_truth_loop_range_10m.pkl"
  dataset: ''
  sequence: ['strawberry/june23/extracted']
  batch_size: 1 #50         # batch size
  workers:  0            # number of threads to get data
  shuffle: False
  loop_range: 10 # Loop Threshold [m]


modelwrapper:
  type: 'ORCHNet'
  minibatch_size: 10


loss:
  type: 'TripletLoss'
  args:
    margin: 0.5
    metric: 'L2' # [L2,Hinge,cosine,kl_divergence]
    reduction: 'mean'


trainer:
  iter_per_epoch: 1
  epochs: 50
  report_val: 1      # every x epochs, report validation set
  save_period: 1
  log_dir: "saved/"
  save_dir: "checkpoints/"
  monitor: "max recall" # [off, max mIoU]
  val_per_epochs: 1
  eval_metric: 'L2'
  results_dir: "/media/tiago/BIG/Orchards/temp/"
  early_stop: 50 #epochs 


optimizer:
  type: "AdamW" #[RMSprop,Adam,SGD]
  args:
    lr: 0.0001
    weight_decay: 0.00000005
  lr_scheduler: "ReduceLROnPlateau"

StepLR:
  step_size: 20 
  gamma: 0.1

CosineAnnealingWarmRestarts:
  T_0: 5
  T_mult: 2
  eta_min: 0.00001 # Min learning rate

ReduceLROnPlateau:
  mode: 'min' #['min','max'] (str)
  factor: 0.01
  patience: 10 # Number of epochs with no improvement after which learning rate will be reduced. 
  min_lr: 0.000001

